//
//  AboutCharacter.swift
//  Star Wars Charaters
//
//  Created by Kinney Kare on 12/14/19.
//  Copyright © 2019 Kinney Kare. All rights reserved.
//

import Foundation


struct AboutCharacter {
    enum Character: String {
        case BB8R2D2C3PO = "R2-D2 is a fictional robot character in the Star Wars franchise. He has appeared in nine of the ten Star Wars films to date. At various points throughout the course of the films, R2 is a friend to C-3PO, Padmé Amidala, Anakin Skywalker, Leia Organa, Luke Skywalker, Obi-Wan Kenobi, BB-8 and Rey. BB-8 is a droid character in the Star Wars franchise, first appearing in the 2015 Star Wars: The Force Awakens. He knows that he can win people over. And he uses that, like children do, to get his own way. In this film, he has a very important mission that he has to accomplish and so he uses his personality, his coyness, and all of those things. C-3PO is a humanoid robot character from the Star Wars franchise who appears in the original trilogy, the prequel trilogy and the sequel trilogy. Built by Anakin Skywalker, C-3PO was designed as a protocol droid intended to assist in etiquette, customs, and translation, boasting that he is \"fluent in over six million forms of communication\". Along with his astromech droid counterpart and friend R2-D2, C-3PO provides comic relief within the narrative structure of the films, and serves as a foil."
        case BobaFett = "Boba Fett is a bounty hunter in the Star Wars franchise. In Episode V – The Empire Strikes Back (1980), he is hired by Darth Vader to capture Han Solo. He also appears at Jabba the Hutt's palace in Episode VI – Return of the Jedi (1983). In 1997, he was retroactively added to the Special Edition of Episode IV – A New Hope. The character is noted for speaking very few words and never removing his helmet in the original trilogy. The prequel film Episode II – Attack of the Clones (2002) establishes Boba Fett's origin as a clone of bounty hunter Jango Fett, who raised him as his son. Boba also appears in episodes of The Clone Wars, bridging his storyline between the two trilogies."
        case Chewbacca = "Chewbacca nicknamed \"Chewie\", is a fictional character in the Star Wars franchise. He is a Wookiee, a tall, hirsute, bipedal, and intelligent species from the planet Kashyyyk. During his long life Chewbacca has been many things: engineer, warrior, slave, smuggler and rebel hero. Chewie fought with the Republic on Kashyyyk during the Clone Wars, then befriended Han Solo while in Imperial captivity on Mimban. Chewbacca is the loyal friend and first mate of Han Solo, and serves as co-pilot on Solo's spaceship, the Millennium Falcon; together they helped the Alliance restore freedom to the galaxy. The character communicates with animal sound growls rather than actual verbal speech."
        case DarthMaul = "Darth Maul, later simply Maul, is a fictional character in the Star Wars franchise. Trained as Darth Sidious' first apprentice, he serves as a Sith Lord and master of wielding a double-bladed lightsaber. He first appears in Star Wars: Episode I – The Phantom Menace (portrayed by Ray Park and voiced by Peter Serafinowicz). He is known for his red and black facial tattoos and the horns atop his head. Despite his apparent demise in that film at the hands of Obi-Wan Kenobi, he later returned in the Star Wars: The Clone Wars animated television series and made further appearances in the Star Wars Rebels series and the 2018 film Solo: A Star Wars Story. "
        case DarthVader = "Originally a Jedi prophesied to bring balance to the Force, Anakin Skywalker is lured to the dark side of the Force by Palpatine, who manipulates his wavering faith towards the Jedi and his fear of possibly losing his secret wife Padmé Amidala and becomes a Sith Lord. After fighting a lightsaber battle with his former mentor Obi-Wan Kenobi in which he is dismembered, Vader is transformed into a cyborg. He then serves the Galactic Empire as Darth Vader until he redeems himself by saving his son, Luke Skywalker, and seemingly killing Palpatine, sacrificing his own life in the process. He is also the father of Princess Leia, and grandfather of Kylo Ren, the main antagonist of the sequel trilogy."
        case EmperorPalpatine = "Palpatine is the main antagonist of the Star Wars franchise. In the original trilogy, he is depicted as emperor of the Galactic Empire and the master of Darth Vader. In the prequel trilogy, he is portrayed as a charismatic Senator from Naboo who uses Machiavellian deception and political manipulation to rise to the position of Supreme Chancellor of the Galactic Republic and transform it into the Empire. Since the initial theatrical run of Return of the Jedi, Palpatine has become a widely recognized symbol of evil in popular culture, and since the prequel films, also one of sinister deception and the subversion of democracy."
        case HanSolo = "Han Solo is a protagonist in the Star Wars franchise, who is a pilot from the planet Corellia. A primary character in the original film trilogy, Han is the captain of the Millennium Falcon, along with his Wookiee co-pilot Chewbacca, whereby both pilots became involved in the Rebel Alliance's struggle against the Galactic Empire after being recruited by Obi-Wan Kenobi and Luke Skywalker. During the course of the Star Wars narrative, Han becomes a chief figure in the Alliance and the love interest of Princess Leia. In the sequel trilogy, Han is Leia's estranged husband and the father of fallen Jedi Kylo Ren. He thinks he's an egoist; but he really isn't. There’s something else pushing him. In 1997, franchise creator George Lucas described Han as \"a cynical loner who realizes the importance of being part of a group and helping for the common good\""
        case KyloRen = "Kylo was introduced in the 2015 film Star Wars: The Force Awakens. \"Kylo Ren\" is the chosen name of Ben Solo, the only son of original Star Wars trilogy characters Han Solo and Leia Organa. Though trained by his uncle Luke Skywalker as a Jedi, he has been seduced to the dark side of the Force by Supreme Leader Snoke and aspires to be as powerful as his grandfather, Darth Vader. Ren is the master of the Knights of Ren, as well as a commander and later the Supreme Leader of the First Order, an organization spawned from the former Galactic Empire. He appears in The Force Awakens, The Last Jedi (2017) and The Rise of Skywalker (2019)."
        case LukeSkywalker = "Luke is the main protagonist of the original film trilogy of the Star Wars franchise. Luke is a pivotal figure in the Rebel Alliance's struggle against the Galactic Empire, a friend and eventual brother-in-law of smuggler Han Solo, and unknown to him until Return of the Jedi, the twin brother of Rebellion leader Princess Leia. He trains under Jedi Masters Obi-Wan Kenobi and Yoda, and is the son of Anakin Skywalker and Padmé Amidala. He mentors Rey, the protagonist of the sequel trilogy, and is the maternal uncle of Kylo Ren, the antagonist of the sequel trilogy. The character also briefly appears in the prequel film Episode III – Revenge of the Sith as an infant. The non-canonical Expanded Universe depicts him as a powerful Jedi Master, the husband of Mara Jade, father of Ben Skywalker and maternal uncle of Jaina, Jacen and Anakin Solo."
        case ObiWanKenobi = "Obi Wan also known as Ben Kenobi, is a character in the Star Wars franchise. In the original trilogy, he is a mentor to Luke Skywalker, to whom he introduces the ways of the Jedi. In the prequel trilogy, set decades earlier, he is a mentor and friend to Luke’s father Anakin, who eventually falls to the dark side of the Force and becomes Darth Vader. He is frequently featured as a main character in various other Star Wars media."
        case PrincessLeia = "Princess Leia was introduced in the original Star Wars film in 1977, Leia is princess of the planet Alderaan, a member of the Imperial Senate and an agent of the Rebel Alliance. She thwarts the sinister Sith lord Darth Vader and helps bring about the destruction of the Empire's cataclysmic superweapon, the Death Star. In The Empire Strikes Back (1980), Leia commands a Rebel base and evades Vader as she falls in love with the smuggler Han Solo. In Return of the Jedi (1983), Leia helps in the operation to rescue Han from the crime lord Jabba the Hutt, and is revealed to be Vader's daughter and the twin sister of Luke Skywalker. The prequel film Revenge of the Sith (2005) establishes that the twins' mother is Senator (and former queen) Padmé Amidala of Naboo, who dies after childbirth. Leia is adopted by Senator Bail and Queen Breha Organa of Alderaan. In the sequel trilogy, Leia is the founder and General of the Resistance against the First Order. She and Han have a son named Ben, who adopted the name Kylo Ren after turning to the dark side of the Force. One of the more popular Star Wars characters, Leia has been called a 1980s icon, a feminist hero and model for other adventure heroines."
        case Rey = "Rey is a fictional character and the main protagonist of the sequel film trilogy of the Star Wars franchise. Rey is a scavenger who was left behind on the planet Jakku when she was a child, and later becomes involved with the Resistance's conflict with the First Order when her solitary life is interrupted by BB-8, the droid of ace Resistance pilot Poe Dameron, and a runaway stormtrooper named Finn."
        case Yoda = "Yoda is a fictional character in the Star Wars universe, first appearing in the 1980 film The Empire Strikes Back. He is a small, green humanoid alien with tremendous power in the Force. In his first appearance in the original trilogy, the spirit of Jedi master Obi-Wan Kenobi describes Yoda as the Jedi master who trained him and asks Luke Skywalker to seek Jedi training from Yoda, which Luke does and later uses to fight against the Galactic Empire. The character reappears in Return of the Jedi where he reveals his age to be 900, making him the oldest living character in the Star Wars franchise. In the prequel trilogy, set a generation before the original trilogy, Yoda is among the most powerful members of the Jedi Order and a general of clone troopers during the Clone Wars. Yoda also trains all Jedi children, before they are assigned a Jedi master. Two other members of Yoda's unnamed alien species are known, although neither is known to be part of Yoda's family. Yaddle (who appears as a background female character in the prequel trilogy film Star Wars Episode I: The Phantom Menace as a Jedi master) and the character in The Mandalorian known currently as \"The Child\" (initially called Baby Yoda by fans). Very little is known about Yoda's alien species, though all three are powerful in The Force."
    }
}

